name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: publish
        env:
          KEY: ${{ secrets.KEY }}
          REMOTE: ${{ secrets.REMOTE }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/gh_actions
          chmod 600 ~/.ssh/gh_actions
          cat >>~/.ssh/config <<END
          Host $HOST
            HostName $HOST
            User $USER
            IdentityFile ~/.ssh/gh_actions
            StrictHostKeyChecking accept-new
          END
          git remote add live $REMOTE
          git push live master
