name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: publish
        env:
          KEY: ${{ secrets.KEY }}
          REMOTE: ${{ secrets.REMOTE }}
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/gh_actions
          chmod 600 ~/.ssh/gh_actions
          git remote add live $REMOTE
          git push live master
